export const defaultRecommendedSeconds = {
  short: 60,
  medium: 150,
  long: 270,
};

export const lengthLabels = {
  short: "단문",
  medium: "중문",
  long: "장문",
};

export const difficultyRank = { N5: 0, N4: 1, N3: 2, N2: 3, N1: 4 };

const items = [
  {
    id: "library",
    status: "held",
    title: "地域の図書館が残すもの",
    officialLevel: "N2",
    perceivedLevel: "N1",
    perceivedVotes: 17,
    lengthType: "medium",
    topic: "교육",
    recommendedSeconds: 150,
    createdAt: "2026-08-28T00:00:00Z",
    updatedAt: "2026-08-29T01:00:00Z",
    publishedAt: null,
    passage: "地域の図書館は、本を借りるためだけの場所ではない。検索すればすぐに答えが見つかる時代だからこそ、何を探せばよいか分からない人が、ゆっくり関心を育てる場所としての役割がある。\n\n図書館員が一人ひとりの問いを聞き、関連する棚へ案内する。そこでは、最初の目的とは少し離れた本に出会うこともある。その偶然が、利用者自身の問いをより具体的な言葉に変えていく。\n\n利用者数や貸出冊数だけでは、この働きは測りにくい。しかし、自分で考え続けるための入口を残すことも、図書館に期待される重要な仕事である。",
    question: "筆者が図書館に期待している役割として最も適切なものはどれか。",
    choices: [
      { id: "library-01", text: "利用者が求めた本だけを、短時間で提供すること。", wrongExplanation: "図書館の役割を速い貸し出しだけに限定しており、本文の主張と合いません。" },
      { id: "library-02", text: "貸出冊数を増やすために、人気の本を集中的にそろえること。", wrongExplanation: "本文は貸出冊数だけでは図書館の働きを測れないと述べています。" },
      { id: "library-03", text: "利用者が関心を言葉にし、新しい知識へつながる場になること。", isCorrect: true },
      { id: "library-04", text: "利用者が偶然に本を選ばないよう、案内を最小限にすること。", wrongExplanation: "本文は偶然の出会いも利用者の問いを育てると説明しています。" },
    ],
    explanation: "글은 도서관이 정답이나 인기 도서만 빠르게 제공하는 곳이 아니라, 이용자가 자신의 관심을 구체적인 질문으로 바꾸고 새로운 지식으로 나아가도록 돕는 장소라고 말합니다. 따라서 03이 가장 적절합니다.",
    quality: 4.3,
    reportCount: 2,
    latestReport: "02번 선택지의 표현이 너무 단정적으로 느껴집니다.",
    validation: { status: "passed", answer: "정답 1개 확인", distractor: "지문 근거와 구분 가능", explanation: "정답 근거와 일치" },
  },
  {
    id: "society",
    status: "published",
    title: "大きな言葉に埋もれる社会",
    officialLevel: "N3",
    perceivedLevel: "N2",
    perceivedVotes: 16,
    lengthType: "long",
    topic: "경제",
    recommendedSeconds: 270,
    createdAt: "2026-08-28T23:00:00Z",
    updatedAt: "2026-08-29T00:00:00Z",
    publishedAt: "2026-08-29T00:00:00Z",
    passage: "駅員と乗客の口論を映した短い動画が流れる。事情はほとんど分からない。それでも数時間後には、「若者の劣化」「高齢者の横暴」「接客業の限界」といった説明が並ぶ。\n\n大きな言葉には力がある。個人の不運に見えるものの背後に、貧困、差別、制度疲労といった構造を見つける。問題は、説明のための枠組みが判決の道具に変わることだ。\n\n必要なのは、個人の経験から構造へ進み、その構造が再び個人にどう作用するかを確かめる往復である。",
    question: "本文全体の主張として最も適切なものはどれか。",
    choices: [
      { id: "society-01", text: "個人の事情よりも集団全体への影響を優先すべきだ。", wrongExplanation: "글은 개인의 사정을 무시하라고 하지 않습니다. 개인의 경험과 사회 구조를 함께 살펴야 한다는 주장과 맞지 않습니다." },
      { id: "society-02", text: "社会構造だけを手がかりに、個別の出来事を理解すべきだ。", wrongExplanation: "사회 구조만으로 사건을 설명하면 개인의 구체적 사정이 사라진다고 글은 지적합니다." },
      { id: "society-03", text: "個人の特殊な事情を除外し、共通要因に基づいて判断すべきだ。", wrongExplanation: "글은 개인의 특수성을 제외하자는 입장이 아니라, 구조와 개인을 오가며 확인해야 한다고 말합니다." },
      { id: "society-04", text: "巨視的な枠組みを仮説として用い、個人と構造の間を往復すべきだ。", isCorrect: true },
    ],
    explanation: "글은 개인의 경험과 사회 구조 중 하나만 택하라고 말하지 않습니다. 두 관점을 오가며 서로 어떻게 영향을 주는지 확인해야 한다는 점에서 04가 가장 적절합니다.",
    quality: 4.6,
    reportCount: 0,
    latestReport: "접수된 오류 제보가 없습니다.",
    validation: { status: "passed", answer: "정답 1개 확인", distractor: "지문 근거와 구분 가능", explanation: "정답 근거와 일치" },
  },
  {
    id: "shopping",
    status: "published",
    title: "夕方の商店街",
    officialLevel: "N2",
    perceivedLevel: "N2",
    perceivedVotes: 12,
    lengthType: "short",
    topic: "생활",
    recommendedSeconds: 60,
    createdAt: "2026-08-25T02:00:00Z",
    updatedAt: "2026-08-28T03:00:00Z",
    publishedAt: "2026-08-28T03:00:00Z",
    passage: "夕方の商店街では、店先に立つ人と買い物袋を抱えた人が短い会話を交わしている。大型店が増えてからも、小さな店を訪れる人がいるのは、品物だけを買いに来るからではない。\n\n顔を覚えてもらい、季節の話をする。そのやり取りは効率だけで測れないが、地域で暮らす人にとっては日常の安心につながっている。",
    question: "筆者が商店街の価値として述べているものはどれか。",
    choices: [
      { id: "shopping-01", text: "大型店より安い品物を提供すること。", wrongExplanation: "本文は価格の安さではなく、人とのやり取りに価値があると述べています。" },
      { id: "shopping-02", text: "地域の人が日常的な関係を築けること。", isCorrect: true },
      { id: "shopping-03", text: "すべての店が同じ営業時間にすること。", wrongExplanation: "営業時間については本文で扱っていません。" },
      { id: "shopping-04", text: "買い物の時間を最短にすること。", wrongExplanation: "本文は効率だけで測れない安心を価値として挙げています。" },
    ],
    explanation: "글은 상점가가 가격이나 속도만으로 설명되지 않는 일상적인 관계와 안심을 제공한다고 말합니다. 따라서 02가 적절합니다.",
    quality: 4.1,
    reportCount: 1,
    latestReport: "지문의 어휘 수준이 N2 기준보다 쉽다는 의견이 있습니다.",
    validation: { status: "passed", answer: "정답 1개 확인", distractor: "지문 근거와 구분 가능", explanation: "정답 근거와 일치" },
  },
  {
    id: "cooking",
    status: "published",
    title: "料理番組が教えないこと",
    officialLevel: "N2",
    perceivedLevel: "N1",
    perceivedVotes: 7,
    lengthType: "medium",
    topic: "요리",
    recommendedSeconds: 150,
    createdAt: "2026-08-19T02:00:00Z",
    updatedAt: "2026-08-19T02:00:00Z",
    publishedAt: "2026-08-19T02:00:00Z",
    passage: "料理番組では、短い時間で見栄えのよい一皿を作るための工夫が紹介される。しかし、家庭の台所では、毎回同じ材料がそろうとは限らず、作る人の体調や時間にも違いがある。\n\n大切なのは、手順を正確に再現することだけではない。材料の状態を見て火加減を変えたり、残った食材を別の料理に生かしたりする判断が、日々の料理を支えている。",
    question: "筆者が日々の料理で大切だと考えていることはどれか。",
    choices: [
      { id: "cooking-01", text: "番組で紹介された手順を毎回正確に再現すること。", wrongExplanation: "本文は手順の再現だけでは不十分だと述べています。" },
      { id: "cooking-02", text: "見栄えのよい料理だけを優先すること。", wrongExplanation: "本文は見栄えよりも日々の状況に応じた判断を重視しています。" },
      { id: "cooking-03", text: "材料や状況に合わせて判断を変えること。", isCorrect: true },
      { id: "cooking-04", text: "毎回同じ材料をそろえて料理すること。", wrongExplanation: "本文は同じ材料がそろわない家庭の状況を前提にしています。" },
    ],
    explanation: "글은 정해진 조리법을 그대로 재현하는 것보다 재료와 상황을 보고 판단을 바꾸는 능력이 일상 요리를 뒷받침한다고 말합니다. 따라서 03이 적절합니다.",
    quality: 0,
    reportCount: 0,
    latestReport: "접수된 오류 제보가 없습니다.",
    validation: { status: "passed", answer: "정답 1개 확인", distractor: "지문 근거와 구분 가능", explanation: "정답 근거와 일치" },
  },
  {
    id: "quiet-library",
    status: "review",
    title: "静かな図書館の役割",
    officialLevel: "N4",
    perceivedLevel: "N4",
    perceivedVotes: 11,
    lengthType: "short",
    topic: "문화",
    recommendedSeconds: 60,
    createdAt: "2026-08-21T01:00:00Z",
    updatedAt: "2026-08-27T04:00:00Z",
    publishedAt: null,
    passage: "静かな図書館では、音を立てないことが目的になりすぎる場合がある。しかし、子どもが質問をしたり、親子で本について話したりする時間までなくしてしまえば、図書館は近づきにくい場所になる。\n\n必要なのは、静けさを一律に守ることではなく、読む人と話す人が互いに利用しやすい環境を考えることである。",
    question: "筆者が図書館の静けさについて最も重視していることはどれか。",
    choices: [
      { id: "quiet-library-01", text: "どの時間でも完全な静けさを守ること。", wrongExplanation: "本文は一律の静けさを守ることを求めていません。" },
      { id: "quiet-library-02", text: "利用者の目的に応じて過ごしやすさを考えること。", isCorrect: true },
      { id: "quiet-library-03", text: "子どもの利用を別の施設へ移すこと。", wrongExplanation: "子どもの質問や会話を排除することは本文の主張と反対です。" },
      { id: "quiet-library-04", text: "会話のある場所をすべてなくすこと。", wrongExplanation: "本文は読む人と話す人の両方が利用しやすい環境を求めています。" },
    ],
    explanation: "글은 정숙 자체보다 읽기와 대화 등 다양한 이용 목적이 공존할 수 있는 환경을 강조합니다. 따라서 02가 적절합니다.",
    quality: 3.8,
    reportCount: 3,
    latestReport: "정답 해설의 표현을 조금 더 구체적으로 보완해 달라는 제보입니다.",
    validation: { status: "warning", answer: "정답 1개 확인", distractor: "지문 근거와 구분 가능", explanation: "해설 표현 보완 권장" },
  },
];

export const initialItems = items;

export const topics = ["생활", "사회", "경제", "과학", "기술", "문화", "여행", "요리", "게임", "교육", "환경"];
